# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- "*"

variables:
  - group: Release
  - name: buildConfiguration
    value: 'Release'
  - name: releaseBranchName
    value: 'release'

schedules:
- cron: '0 19 * * *'
  displayName: 'Deploy every day at 10 A.M. UTC'
  branches:
    include:
    - release
  always: false 

stages:
- stage: 'Build'
  displayName: 'Building Application'
  jobs:
  - job: 'Build'
    displayName: 'Build Job'

    pool:
      name: LOCAL
      demands:
        - npm

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - script: npx node-sass $(wwwrootDir) --output $(wwwrootDir)
      displayName: 'Sass'

    - task: gulp@1
      displayName: 'Gulp run'

    - script: echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
      displayName: 'Buildinfo creation'
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        vstsFeed: 'Tailspin.SpaceGame.Web.Models'
        projects: '**/*.csproj'

    - template: templates/build.yml
      parameters:
        buildConfiguration: $(buildConfiguration)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      condition: succeeded()

- stage: 'Dev'
  displayName: 'Deploy the dev env'
  dependsOn: Build
  condition: |
    and (
    succeeded(),
    eq(variables['Build.SourceBranchName'], variables['releaseBranchName']))
  jobs:
  - template: templates/deploy.yml
    parameters:
      WebAppName: '$(WebAppNameDev)'
      environment: dev

- stage: 'Test'
  displayName: 'Deploy the QA env'
  dependsOn: Dev
  condition: |
    and (
    succeeded(),
    or (eq(variables['Build.Reason'],'Schedule'), eq(variables['Build.Reason'],'Manual')))
  jobs:
  - template: templates/deploy.yml
    parameters:
      WebAppName: '$(WebAppNameTest)'
      environment: test

- stage: 'Staging'
  displayName: 'Deploy the Staging env'
  dependsOn: Test
  jobs:
  - deployment: Deploy
    pool:
      name: LOCAL
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            patterns: |
                **/*.zip
                !**/*.Tests.zip
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deployment'
            inputs:
              azureSubscription: 'ARM-Tailspin'
              deployToSlotOrASE: 'true'
              resourceGroupName: 'webapp-rg1'
              slotName: 'swap'
              appName: '$(WebAppNameStaging)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
          - task: AzureAppServiceManage@0
            displayName: 'Swap deployment slots'
            inputs:
              azureSubscription: 'ARM-Tailspin'
              resourceGroupName: 'webapp-rg1'
              webAppName: '$(WebAppNameStaging)'
              sourceSlot: 'swap'
              targetSlot: 'production'
              action: 'Swap Slots'
 
  - job: 'LoadTests'
    dependsOn: Deploy
    displayName: 'Running load tests with JMeter'
    pool:
      name: LOCAL
    
    steps:
    - script: |
        wget -c archive.apache.org/dist/jmeter/binaries/apache-jmeter-$(jmeter_version).tgz
        tar -xzf apache-jmeter-$(jmeter_version).tgz
      displayName: 'Install Apache JMeter'
    - script: apache-jmeter-$(jmeter_version)/bin/./jmeter -n -t LoadTest.jmx -o Results.xml -Jhostname=$(STAGING_HOSTNAME) 
      displayName: 'Running tests'
    - script: xsltproc JMeter2JUnit.xsl Results.xml > JUnit.xml
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: JUnit.xml