# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- "*"

variables:
  - group: Release
  - name: buildConfiguration
    value: 'Release'
  - name: releaseBranchName
    value: 'docker'
  - name: webRepository
    value: 'web'
  - name: tag
    value: '$(Build.BuildId)'


stages:
- stage: 'Build and Push'
  displayName: 'Building and Push container'
  jobs:
  - job: 'Build'
    displayName: 'Build Job'

    pool:
      name: LOCAL
      demands:
        - npm

    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        containerRegistry: 'ACR-Tailspin'
        tags: |
          $(tag)
    
- stage: 'Dev'
  displayName: 'Deploy the dev container'
  dependsOn: Build
  condition: |
    and (
    succeeded(),
    eq(variables['Build.SourceBranchName'], variables['releaseBranchName']))
  jobs:
   - job: 'Deploy'
     displayName: 'Deploy Container'
     pool:
      name: LOCAL
      demands:
        - npm
    
     steps:
     - task: AzureWebAppContainer@1
       inputs:
       appName: $(WebAppName)
       azureSubscription: 'ARM-Tailspin'
       imageName: $(RegistryName)/$(webRepository):$(build.buildId)  

