# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- build-pipeline

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: npx node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot
  displayName: 'Sass'

- task: gulp@1
  displayName: 'Gulp run'

- script: echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: 'Buildinfo creation'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
